import type { JobCategory } from "@/features/jobs/types/job";

export const JOB_LOCATIONS = [
  "Bagerhat",
  "Bandarban",
  "Barguna",
  "Barisal",
  "Bhola",
  "Barishal Metro",
  "Bogra",
  "Brahmmanbaria",
  "Chandpur",
  "Chapai Nawabganj",
  "Chittagong",
  "Chuadanga",
  "Chottogram Metro",
  "Cox's Bazar",
  "Cumilla",
  "Dhaka",
  "Dinajpur",
  "Dhaka Metro",
  "Faridpur",
  "Feni",
  "Gaibandha",
  "Gazipur",
  "Gazipur Metro",
  "Gopalgonj",
  "Habigonj",
  "Jamalpur",
  "Jessore",
  "Jhalokathi",
  "Jhenaidah",
  "Joypurhat",
  "Khagrachari",
  "Khulna",
  "Kishoregonj",
  "Khulna Metro",
  "Kurigram",
  "Kustia",
  "Lalmonirhat",
  "Laxmipur",
  "Madaripur",
  "Magura",
  "Manikgonj",
  "Meherpur",
  "Moulabhibazar",
  "Munshigonj",
  "Mymensingh",
  "Naogaon",
  "Narail",
  "Narayangonj",
  "Narsingdi",
  "Natore",
  "Netrokona",
  "Nilphamari",
  "Noakhali",
  "Pabna",
  "Panchagarh",
  "Patuakhali",
  "Pirojpur",
  "Rajbari",
  "Rajshahi",
  "Rangamati",
  "Rangpur",
  "Rajshahi Metro",
  "Rangpur Metro",
  "Saint Martin",
  "Satkhira",
  "Shariatpur",
  "Sherpur",
  "Sirajgonj",
  "Sylhet Metro",
  "Srimangal",
  "Sunamgonj",
  "Sylhet",
  "Tangail",
  "Teknaf",
  "Thakurgaon",
] as const;

export const JOB_CATEGORIES: JobCategory[] = [
  { label: "All Category", count: 25 },
  { label: "Administration", count: 5 },
  { label: "Asset Management", count: 3 },
  { label: "Accounts Officer", count: 4 },
  { label: "Branch Banking", count: 10 },
  { label: "Technology", count: 3 },
];

export const JOB_SORT_OPTIONS = [
  "SortBy Newest",
  "SortBy Oldest",
  "SortBy Popular",
  "SortBy Trending",
] as const;
